### ISSUE TITLE
Breaking interiors

### ISSUE THREAD

**Issue by AndreasFromDanmark** [ActuallyStrez/qb-tsunami#15]
Water is everywhere in underground interiors

![image](https://github.com/ActuallyStrez/qb-tsunami/assets/35656492/4f37207b-140d-4a50-b63a-85d3665bf651)

**Comment by ActuallyStrez** [comment]
Yes, Im aware off this issue and few other issues the water is causing, Im trying to solve this but its being a nightmare within the water quads stuff.
