### ISSUE TITLE
World under water

### ISSUE THREAD

**Issue by DevOzzy** [ActuallyStrez/qb-tsunami#17]
Having this script in I noticed the subway is under water. Same with a hospital mlo that had a lower level. Once we took it out the water was gone.

**Comment by rockstarrepublic1** [comment]
Same. All of my TP locations for qb-housing is the same way, along with drug scripts. Everything else in the script works fine, just take out the water raising code because it causes too many issues.

**Comment by solarisrp** [comment]
My issue a little bit bigger. because it has flooded all my IPLS. and even when I remove the script they are still flooded. I need help! luckily this is all on my dev server but it makes testing difficult

**Comment by rockstarrepublic1** [comment]
I ended up commenting out  lines 8-11 and 310-352 in the client\main.lua.

**Comment by JSON-135** [comment]
So i was able to fix it

Remove 
`AddEventHandler('onClientResourceStart', function(resourceName)
    if (GetCurrentResourceName() ~= resourceName) then
        return
    end
    local success = LoadWaterFromPath(GetCurrentResourceName(), 'flood.xml')
    local waterQuadCount = GetWaterQuadCount()
    local calmingQuadCount = GetCalmingQuadCount()
    local waveQuadCount = GetWaveQuadCount()
end)`

From the Strez Tsunami section at the top of the client/main.lua

So you are only left with only
`-------------------- Strez Tsunami --------------------
local QBCore = exports['qb-core']:GetCoreObject()`

then you add
`	local success = LoadWaterFromPath(GetCurrentResourceName(), 'flood.xml')
    local waterQuadCount = GetWaterQuadCount()
    local calmingQuadCount = GetCalmingQuadCount()
    local waveQuadCount = `GetWaveQuadCount()``

So any of the NetEvents where emails or other things get triggered. For example mine is in
`RegisterNetEvent('strez:client:SendMailTsunamiAuto1', function(text)`

### Full example of the full NetEvent (Please note i edited my net events to my liking so it doesn't look the exact same, plus i added a Siren to the file and interact-sounds)
`RegisterNetEvent('strez:client:SendMailTsunamiAuto1', function(text)
    local message = 'Critical alert: A tsunami is imminent. This is a life-threatening situation. Evacuate immediately to higher ground if you are in a coastal area. Follow all emergency instructions. Stay safe and avoid all low-lying areas.'
    
    -- Load the flood.xml file when the tsunami alert is triggered
	local success = LoadWaterFromPath(GetCurrentResourceName(), 'flood.xml')
    local waterQuadCount = GetWaterQuadCount()
    local calmingQuadCount = GetCalmingQuadCount()
    local waveQuadCount = GetWaveQuadCount()
    
    -- Notify players
    Wait(5000)
    if Config.Notify == 'qb' then
        TriggerEvent('QBCore:Notify', message, 'success', 15000)
    elseif Config.Notify == 'ox' then
        lib.notify({ description =  message, duration = 15000, type = 'info', position = 'top-right' })
    elseif Config.Notify == 'email' then
        if Config.Phone == 'qb' then
            TriggerServerEvent('qb-phone:server:sendNewMail', {
                sender = 'District of Los Santos',
                subject = 'Emergency Broadcast',
                message =  message,
                button = {}
            })
        elseif Config.Phone == 'qs' then
            TriggerServerEvent('qs-smartphone:server:sendNewMail', {
                sender = 'District of Los Santos',
                subject = 'Emergency Broadcast',
                message =  message,
                button = {}
            })
        elseif Config.Phone == 'gks' then
            TriggerServerEvent('gksphone:NewMail', {
                sender = "City of Los Santos",
                subject = "Emergency Broadcast",
                message = message,
                button = {}
            })
        end
    end
    
    TriggerEvent('strez:raisewater')
    Wait(82000)
    TriggerEvent('InteractSound_CL:PlayOnOne', 'AirSiren', 0.5)
end)`

**Comment by JSON-135** [comment]
@ActuallyStrez
