### ISSUE TITLE
Floods RTX MLO Club77

### ISSUE THREAD

**Issue by YoruNeko-707** [ActuallyStrez/qb-tsunami#18]
Hello,

I noticed the default water level for this script floods RTX's MLO Club77. How do I lower the default water level so that its peak is below the bottom of the floor where my character stands at z=-0.98?

**Comment by YoruNeko-707** [comment]
Also I noticed the subway is flooded starting in La Puerta heading south. The flooding gets worse the further south of the map your character gets, to where the two terminals near the airport are completely flooded. I understand if this was during the tsunami times, but this is default......

**Comment by ActuallyStrez** [comment]
Hey, So iv never heard of Club77 MLO, However, i am currently aware of the water level issue. I have been trying to find a solution for this but haven't been able to find one, And I don't really do anything todo with FiveM anymore. But I do still look from time to time to see if I can solve this. I have a look within few days but until then I don't know what else todo for you sorry

**Comment by rockstarrepublic1** [comment]
Same thing is happening for me. All of my TP locations for qb-housing are the same way, along with drug scripts. Everything else in the script works fine, just take out the water raising code because it causes too many issues.

**Comment by JSON-135** [comment]
> Hello,
> 
> I noticed the default water level for this script floods RTX's MLO Club77. How do I lower the default water level so that its peak is below the bottom of the floor where my character stands at z=-0.98?

Check out my comments on: https://github.com/ActuallyStrez/qb-tsunami/issues/17
