### ISSUE TITLE
sound?

### ISSUE THREAD

**Issue by hoodz123** [ActuallyStrez/qb-tsunami#2]
Put Sound In The Interact And The Email Goes Through Put The SOUND Dont Play?

**Comment by hoodz123** [comment]
yeah everything in when i do the coming it dont play the sound about 10secs after the email comes through but no sound as i say im on latest of qb aswell

**Comment by ActuallyStrez** [comment]
Okay, I'm gonna take a look shortly and I let you know. Thanks

**Comment by ActuallyStrez** [comment]
Updated, Should all be working now. Removed some useless code.
