### ISSUE TITLE
GKS-phone

### ISSUE THREAD

**Issue by Roosterbrood** [ActuallyStrez/qb-tsunami#4]
I can find the place to change the use of GKS-phone

**Comment by ActuallyStrez** [comment]
If you are using https://fivem.gkshop.org/package/4862478 (QBCore)

You will need to edit the follow lines and replace with this.

Search "TriggerServerEvent('qb-phone:server:sendNewMail', {"

Replace with "TriggerServerEvent('gksphone:NewMail', {"

Also you will need to remove the qb-phone Dependencie from the fxmanifest
