### ISSUE TITLE
Siren

### ISSUE THREAD

**Issue by FransFX** [ActuallyStrez/qb-tsunami#8]
The sirens doesnt go of..Any idea?

**Comment by ActuallyStrez** [comment]
Did you add the sound file to interact sounds?

**Comment by FransFX** [comment]
there is no interact or sound file...

**Comment by FransFX** [comment]
unless i am missing something. there is only a server, client and config

**Comment by ActuallyStrez** [comment]
look in the setup folder its in there

**Comment by FransFX** [comment]
it is in there. where do i put it then?
do i make a new folder called interact sounds?

**Comment by ActuallyStrez** [comment]
Read the readme bro! Everything you need to know is there. Everything works perfect if you follow it correctly.

**Comment by FransFX** [comment]
Did that BRO. Doesnt work

**Comment by ActuallyStrez** [comment]
mmm then your done something wrong then bro, Generally nothing else I can suggest to you

**Comment by FransFX** [comment]
Yeah okay bro
