### ISSUE TITLE
A way to turn off ragdoll and camera shake

### ISSUE THREAD

**Issue by Blazono** [ActuallyStrez/qb-tsunami#9]
I have tried editing out the function TsunamiEffect in its entirety - but still no avail. is there a way that this can be pulled to add true/false options for cam shake and ragdoll effect?

**Comment by ActuallyStrez** [comment]
Just disabled this line TsunamiEffect in client side on the events, Also be updating it next couple days and will be removing all camera shakes etc and just cleaning up the code, Sorry for the delay in reply
